# pre-install

addons:
  apt:
    packages:
    - docker
    - curl
    
before_install:
  - sudo ./install-docker-compose.sh

install: true

# build

sudo: required

before_script:
  - sudo /etc/init.d/mysql stop

script: 
  - ./do-it-all.sh
