# pre-install

addons:
  apt:
    packages:
    - docker
    - curl
    
before_install:
  - sudo ./install-docker-compose.sh

install: true

# build

before_script: true

script: 
  - ./do-it-all.sh
