# pre-install

addons:
  apt:
    packages:
    - docker
    - curl
    
before_install:
  - ./install-docker-compose.sh

install: true

# build

before_script: true

script: 
  - echo "Building spring-boot app #1"
  - docker build -t pet-clinic-01 .
  - echo "Building spring-boot app #2"
  - docker build -t pet-clinic-02 .
  - echo "Spinning up docker-compose"
  - docker-compose down
  - docker-compose up -d
  - echo "Docker-compose status:"
  - docker-compose ps
  - echo "dc down"
  - docker-compose down
