version: "3"
services:
    mysql:
        build: pc-mysql/.
        container_name: pc-mysql
        ports:
          - "3306:3306"
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "--silent"]
          interval: 1m30s
          timeout: 15s
          retries: 3
          #start_period: 1m1s

    pet-clinic-01:
        image: pet-clinic-01
        container_name: pet-clinic-01
        links:
         - mysql:mysql
        ports:
         - "3001:8080"
        depends_on:
         - mysql

    pet-clinic-02:
        image: pet-clinic-01
        container_name: pet-clinic-02
        links:
         - mysql:mysql
        ports:
         - "3002:8080"
        depends_on:
         - mysql

    ngnx:
        build: ngnx/.
        container_name: pc-nginx
        links:
         - pet-clinic-01:pet-clinic-01
         - pet-clinic-02:pet-clinic-02
        ports:
          - "80:80"
          - "443:443"
          - "8081:8081"
        depends_on:
          - pet-clinic-01
          - pet-clinic-02
