version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: localhost:5000/amir-3
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 2000M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
