mysql:
  image: pc-mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
    
pet-clinic-01:
    image: pet-clinic-01
    container_name: pet-clinic-01
    links:
     - mysql:mysql
    ports:
     - "3001:8080"

pet-clinic-02:
    image: pet-clinic-02
    container_name: pet-clinic-02
    links:
     - mysql:mysql
    ports:
     - "3002:8080"

ngnx:
    image: pc-nginx
    container_name: pc-nginx
    links:
     - pet-clinic-01:pet-clinic-01
     - pet-clinic-02:pet-clinic-02
    ports:
     - "80:80"
     - "443:443"
     - "8081:8081"
