kind: Service
apiVersion: v1
metadata:
  #Service name
  name: pet-clinic-svc
spec:
  selector:
    app: pet-clinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
